# Generated by Django 3.1.1 on 2020-10-27 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201027_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='addres',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='custumer',
            new_name='customer',
        ),
    ]
